sudo: required

language: c

env:
  global:
    - OPENSSL_INSTALL_DIR="${HOME}/opt"

matrix:
  include:
    - env: OPENSSL_VERSION="1.0.2o" CC=clang-5.0 CXX=clang++-5.0
      os: linux
      compiler: gcc

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages: [ g++-7, clang-5.0, debhelper, devscripts, fakeroot, cmake3, dh-exec ]

cache:
  directories:
  - download-cache
  - ${HOME}/opt

before_install:
  - bash .ci/build-openssl.sh > build-deps.log 2>&1 || (cat build-deps.log && exit 1)

script:
  - export OPENSSL_ROOT_DIR=${OPENSSL_INSTALL_DIR}
  - export LD_LIBRARY_PATH="${HOME}/opt/lib:${LD_LIBRARY_PATH:-}"
  - export CFLAGS="-I${HOME}/opt/include -fsanitize-coverage=trace-pc-guard,indirect-calls,trace-cmp,trace-gep,trace-div,pc-table,edge"
  - export LDFLAGS="-L${HOME}/opt/lib"
  - ./configure
  - make -C tmp
  - ldd bin/vpnserver/vpnserver
  - if [ "${BUILD_DEB}" = "1" ]; then make package -C tmp; fi
