sudo: required

language: c

env:
  global:
    - OPENSSL_INSTALL_DIR="${HOME}/opt"

matrix:
  include:
    - env: OPENSSL_VERSION="1.0.2o" BUILD_DEB="1"
      os: linux
      compiler: gcc
    - env: OPENSSL_VERSION="1.1.0f"
      os: linux
      compiler: gcc
    - env: OPENSSL_VERSION="1.0.2o"
      os: linux
      compiler: clang
    - env: OPENSSL_VERSION="1.1.0f"
      os: linux
      compiler: clang
    - env: DESCRIPTION="experimental OpenWRT build"
      os: linux
      before_script:
        - git clone https://github.com/openwrt/openwrt.git
        - cd openwrt
        - echo "src-git softethervpn https://github.com/Andy2244/openwrt-extra.git" >> feeds.conf.default
        - ./scripts/feeds update
        - ./scripts/feeds install softethervpn
        - make defconfig
      script:
        - make package/softethervpn/compile PKG_SOURCE_COMMIT=${TRAVIS_COMMIT} V=99 -j1 V=s
    - os: osx
      compiler: clang
      cache:
        directories:
        - ${HOME}/Library/Caches/Homebrew
      before_install:
        - brew update && brew upgrade
      script:
        - ./configure
        - make -C tmp
        - otool -L bin/vpnserver/vpnserver

addons:
  apt:
    packages: [ debhelper, devscripts, fakeroot, cmake3, dh-exec ]

cache:
  directories:
  - download-cache
  - ${HOME}/opt

before_install:
  - bash .ci/build-openssl.sh > build-deps.log 2>&1 || (cat build-deps.log && exit 1)

script:
  - export OPENSSL_ROOT_DIR=${OPENSSL_INSTALL_DIR}
  - export LD_LIBRARY_PATH="${HOME}/opt/lib:${LD_LIBRARY_PATH:-}"
  - export CFLAGS="-I${HOME}/opt/include"
  - export LDFLAGS="-L${HOME}/opt/lib"
  - ./configure
  - make -C tmp
  - ldd bin/vpnserver/vpnserver
  - if [ "${BUILD_DEB}" = "1" ]; then make package -C tmp; fi
